config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lessonmgmt/', include('lessonmgmt.urls')),
]

# [teldren]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

lessonmgmt/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'lessonmgmt'
urlpatterns = [
    # メニュー
    path('menu/', views.menu_view.MenuView.as_view(), name='menu_list'),
    # 顧客一覧
    path('customer/', views.customer_view.CustomerListView.as_view(), name='customer_list'), # 一覧
    path('customer/add/', views.customer_view.CustomerCreateView.as_view(), name='customer_add'), # 新規登録
    path('customer/update/<uuid:pk>/', views.customer_view.CustomerUpdateView.as_view(), name='customer_update'), # 修正
    path('customer/delete/<uuid:pk>/', views.customer_view.CustomerDeleteView.as_view(), name='customer_delete'), # 削除
    # ジャンル一覧
    path('lesson/', views.lesson_view.LessonListView.as_view(), name='lesson_list'), # 一覧
    path('lesson/add/', views.lesson_view.LessonCreateView.as_view(), name='lesson_add'), # 登録
    path('lesson/update/<uuid:pk>/', views.lesson_view.LessonUpdateView.as_view(), name='lesson_update'), # 修正
    path('lesson/delete/<uuid:pk>/', views.lesson_view.LessonDeleteView.as_view(), name='lesson_delete'),  # 削除
    # 受講履歴一覧
    path('lessonhistory/', views.lessonhistory_view.LessonHistoryListView.as_view(), name='lessonhistory_list'),  # 一覧
    path('lessonhistory/add/', views.lessonhistory_view.LessonHistoryCreateView.as_view(), name='lessonhistory_add'), # 登録
    path('lessonhistory/edit/<uuid:pk>/', views.lessonhistory_view.LessonHistoryUpdateView.as_view(), name='lessonhistory_update'), # 修正
    path('lessonhistory/delete/<uuid:pk>/', views.lessonhistory_view.LessonHistoryDeleteView.as_view(), name='lessonhistory_delete'),  # 削除
    # 請求一覧
    path('invoice/', views.invoice_view.InvoiceView.as_view(), name='invoice_search_form'),   # 検索フォーム
    path('invoice/filter', views.invoice_view.InvoiceFilterView.as_view(), name='invoice_filter'),   # 検索結果画面
    # レポート
    path('report/', views.report_view.ReportView.as_view(), name='report_search_form'),   # 検索フォーム
    path('report/genre_gender_age', views.report_view.GenreGenderAgeFilterView.as_view(), name='report_genre_gender_age'),   # ジャンル年齢レポート画面
]
# Add comments.

lessonmgmt/forms/customer_form.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from lessonmgmt.models.customer import *

class CustomerForm(ModelForm):
    """
    受講者情報の入力用フォーム
    """
    class Meta:
        model = Customer
        fields = ('name', 'gender', 'age', )

lessonmgmt/forms/lesson_form.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from django.forms import ModelForm
from lessonmgmt.models.lesson import *
import json

class LessonForm(ModelForm):
    """
    ジャンル情報の入力用フォーム
    """
    class Meta:
        model = Lesson
        fields = ('lessonName', 'basicCharge', 'includeHour', 'hourlyRate')

    def clean_hourlyRate(self):
        """
        従量課金情報のバリデーション
        e.g. [{"hour" : 0, "rate" : 1500}, {"hour" : 20, "rate" : 1000}, {"hour" : 35, "rate" : 800}]
        """
        hourlyRate  = self.cleaned_data['hourlyRate']
        try:
            hourlyRate_json = json.loads(hourlyRate)
            json_length = len(hourlyRate_json)
            if json_length == 0:
                raise forms.ValidationError()
            for i in range(0, json_length):
                hourlyRate_json[i]["hour"]
                hourlyRate_json[i]["rate"]
        except:
            raise forms.ValidationError(u'有効なJson形式ではありません')

        return hourlyRate

lessonmgmt/views/customer_lesson_history_table.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django_pandas.io import read_frame
import pandas as pd
import json
import numpy as np
import datetime

from lessonmgmt.models.customer import *
from lessonmgmt.models.lesson import *
from lessonmgmt.models.lessonhistory import *
from dateutil.relativedelta import relativedelta

class CustomerLessonHistoryTable:
    """
    請求情報，レポート情報を取得するためのクラス

    :param select_month: 選択月
    :param startDate: 選択月初日
    :param endDate: 選択月末日
    :param all_table_df: 顧客一覧を受講履歴一覧とLeft Outer Joinした結果
    :param lesson_df: ジャンル一覧
    :param customers_df: 顧客一覧

    :param basicCharge_dict: 料金計算で利用するapply関数(calculate_invoice)で使う変数
    :param includeHour_dict: 料金計算で利用するapply関数(calculate_invoice)で使う変数
    :param hourlyRate_dict: 料金計算で利用するapply関数(calculate_invoice)で使う変数
    :param lessonHours_dict: 料金計算で利用するapply関数(calculate_invoice)で使う変数
    """
    def __init__(self, select_month):
        self.select_month = select_month
        self.startDate = datetime.datetime.strptime(select_month, '%Y-%m-%d')
        self.endDate = self.startDate + relativedelta(months=1) - relativedelta(days=1)
        self.all_table_df = None
        self.lesson_df = read_frame(Lesson.objects.all())

    def get_all_table(self):
        """
        顧客一覧を受講履歴一覧とLeft Outer Joinした結果を返す。
        顧客一覧と受講履歴一覧をDBより取得し，PandasのDataFrameへ変換。
        Pandasの機能を使って，Left Outer Joinを実施し，DataFrameを返す。

        Returns:
            DataFrame: self.all_table_df

        Columns of self.all_table_df:
            'customer_id', 'name', 'gender', 'age',
            'lessonName_id', 'lessonHours', 'lessonName',
            'lessonName_basicCharge', 'lessonName_includeHour',
            'lessonName_hourlyRate', 'Json_hourlyRate', 'Total_Price', 'index_val'
        """
        if self.all_table_df is not None:
            return self.all_table_df
        # [teldren] 顧客リスト
        self.customers_df = read_frame(Customer.objects.all())
        if len(self.customers_df.index) == 0:
            return pd.DataFrame()

        # [teldren] 受講履歴リスト，ジャンル情報付きで取得。対象月でフィルタリング。
        lessonhistories = LessonHistory.objects.filter(lessonDate__gte=self.startDate,
                                                       lessonDate__lte=self.endDate)\
                                               .select_related()\
                                               .order_by('lessonDate')
        # [teldren] 受講履歴がない場合，顧客一覧に受講無し情報を付与する
        lessonhistories_df = pd.DataFrame()
        if lessonhistories.count() == 0:
            df = self.customers_df
            df.loc[:,'lessonName'] = '-----'
            df.loc[:,'lessonHours'] = 0
            df.loc[:,'Total_Price'] = 0
            return df
        # [teldren] lessonhistoriesの検索結果をPandasのDataFrameへ変換する。
        for lessonhistory in lessonhistories:
            lessonhistories_df = pd.concat([lessonhistories_df,lessonhistory.get_pandas_dataframe()])

        # [teldren] 顧客リストと受講履歴リストを外部結合。受講履歴のない顧客も抽出するため。
        customer_lessonhistories_df = pd.merge(self.customers_df, lessonhistories_df,
                                               left_on='customer_id',
                                               right_on='customerName_id',
                                               how='left')
        # [teldren] 受講履歴のない顧客レコードのジャンル名，従量料金，レッスン時間がNaNになるため，'-----'，空Json，0とを代入。
        customer_lessonhistories_df = customer_lessonhistories_df.fillna({'lessonName':'-----',
                                                                          'lessonName_id':'Null',
                                                                          'lessonName_hourlyRate': '{}',
                                                                          'lessonHours': 0})
        # [teldren] 顧客id，ジャンルidで集計(GroupBy)
        df = customer_lessonhistories_df[['name', 'customer_id', 'gender', 'age',
                                          'lessonName_id', 'lessonHours']]\
                                          .groupby(['customer_id', 'name', 'gender', 'age', 'lessonName_id'])\
                                          .sum().reset_index()
        # [teldren] 上記集計結果へ結合するためのジャンル情報を抽出
        lessonInfo = customer_lessonhistories_df[['lessonName', 'lessonName_id',
                                                  'lessonName_basicCharge', 'lessonName_includeHour',
                                                  'lessonName_hourlyRate']].drop_duplicates()

        # [teldren] 従量課金情報を文字列からJson形式へ一括変換。結合前に，lessonInfoのhourlyRateをリスト形式に変換する。
        lessonInfo.loc[:,'Json_hourlyRate'] = lessonInfo.lessonName_hourlyRate.apply(self.str2json_hourlyrate)
        # [teldren] 集計結果とジャンル情報を結合
        df = pd.merge(df, lessonInfo, on='lessonName_id', how='left')
        df.loc[:,'Total_Price'] = 0
        # [teldren] apply関数calculate_report用のdictionaryとindexを用意
        self.basicCharge_dict = df.lessonName_basicCharge.to_dict()
        self.includeHour_dict = df.lessonName_includeHour.to_dict()
        self.hourlyRate_dict = df.Json_hourlyRate.to_dict()
        self.lessonHours_dict = df.lessonHours.to_dict()
        df.loc[:,'index_val'] = df.index
        df.loc[:,'Total_Price'] = df.index_val.apply(self.calculate_invoice)
        self.all_table_df = df

        return self.all_table_df

    def get_all_table_innerjoin(self):
        """
        顧客一覧と受講履歴のLeft Joinした結果を返す。
        """
        return self.get_all_table().dropna()

    def get_invoices(self):
        """
        全顧客の請求情報を返す。
        顧客情報がない場合，空のDataFrameが返る。

        Returns:
            DataFrame: invoices_df

        Columns of invoices_df:
            'customer_id', 'name', 'lessonHours', 'Total_Price', 'lessonName'
        """
        df = self.get_all_table()
        if len(df.index) == 0:
            return df

        invoices_df = df[['customer_id', 'name',
                          'lessonName', 'lessonHours', 'Total_Price']]\
                          .groupby(['customer_id', 'name'])\
                          .apply(self.groupby_name)\
                          .reset_index()
        return invoices_df

    def get_reports_genre_gender(self):
        """
        ジャンルと性別毎での売上を返す。

        Returns:
            DataFrame: rslt_df

        Columns of rslt_df:
            'lessonName', 'gender', 'lessonHours', 'customerCount', 'Total_Price'
        """
        genre_gender_master_df = self._create_genre_gender_master()
        df = self.get_all_table_innerjoin()
        if len(df.index) == 0:
            genre_gender_master_df['lessonHours'] = 0
            genre_gender_master_df['customerCount'] = 0
            genre_gender_master_df['Total_Price'] = 0
            return genre_gender_master_df
        df.loc[:,'customerCount'] = 0
        genre_gender_df = df.groupby(['lessonName', 'gender'])\
                            .agg({'lessonHours':'sum', 'customerCount':'count', 'Total_Price':'sum'})\
                            .reset_index()
        genre_gender_master_df = self._create_genre_gender_master()
        rslt_df = pd.merge(genre_gender_master_df, genre_gender_df,
                           left_on=['lessonName', 'gender'],
                           right_on=['lessonName', 'gender'], how='left')
        return rslt_df.fillna(0)

    def get_reports_genre_age(self):
        """
        ジャンル，性別毎，年齢毎での売上を返す。

        Returns:
            DataFrame: rslt_df

        Columns of rslt_df:
            'lessonName', 'gender', 'age', 'lessonHours', 'customerCount', 'Total_Price'
        """
        genre_gender_age_master_df = self._create_genre_gender_age_master()
        df = self.get_all_table_innerjoin()
        if len(df.index) == 0:
            genre_gender_age_master_df.loc[:,'lessonHours'] = 0
            genre_gender_age_master_df.loc[:,'customerCount'] = 0
            genre_gender_age_master_df.loc[:,'Total_Price'] = 0
            return genre_gender_age_master_df
        df.loc[:,'customerCount'] = 0
        #labels = [ "{0} - {1}".format(i, i + 9) for i in range(0, 100, 10) ]
        labels = [ "{0} 代".format(i) for i in range(0, 100, 10) ]
        cut_age = pd.cut(df.age, np.arange(0, 101, 10),
           include_lowest=True, right=False, labels=labels)
        genre_age_df = df.groupby(['lessonName', 'gender', cut_age])\
                         .agg({'lessonHours':'sum', 'customerCount':'count', 'Total_Price':'sum'})\
                         .reset_index()
        rslt_df = pd.merge(genre_gender_age_master_df, genre_age_df,
                           left_on=['lessonName', 'gender', 'age'],
                           right_on=['lessonName', 'gender', 'age'], how='left')
        return rslt_df.fillna(0)

    def calculate_invoice(self, idx):
        """
        料金計算をする，Pandasのapply用関数

        Returns:
            float: invoice
        """
        invoice = 0
        lessonHours = self.lessonHours_dict[idx]
        if lessonHours == 0:
            return invoice

        basicCharge = self.basicCharge_dict[idx]
        includeHour = self.includeHour_dict[idx]
        hourlyRate = self.hourlyRate_dict[idx]
        invoice = basicCharge
        not_find = True
        for rate in reversed(hourlyRate):
            if not_find:
                if lessonHours > rate['hour']:
                    invoice += (lessonHours-rate['hour'])*rate['rate']
                    before_hour = rate['hour']
                    not_find = False
            else:
                invoice += (before_hour - rate['hour'])*rate['rate']
                before_hour = rate['hour']
        # [teldren] 基本料金に含まれる時間分の料金を除く。
        invoice = invoice - includeHour*hourlyRate[0]['rate']
        if invoice < 0:
            invoice = 0
        return invoice


    def str2json_hourlyrate(self, hourlyrate):
        """
        従量課金情報の文字列をJson形式に変換する，Pandasのapply用関数。

        Returns:
            Json: hourlyrate_json
        """
        hourlyrate_json = json.loads(hourlyrate)
        return hourlyrate_json

    def groupby_name(self, ser):
        """

lessonmgmt/views/customer_view.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy

from lessonmgmt.models.customer import *
from lessonmgmt.forms.customer_form import *

# Create your views here.
class CustomerListView(ListView):
    """
    受講者一覧を表示
    """
    template_name = 'lessonmgmt/customer_list.html'
    model = Customer

class CustomerCreateView(CreateView):
    """
    受講者新規追加
    """
    template_name = 'lessonmgmt/customer_update.html'
    model = Customer
    form_class = CustomerForm
    success_url = reverse_lazy('lessonmgmt:customer_list')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(
            self.request, '「{}」を作成しました'.format(form.instance))
        return result

class CustomerUpdateView(UpdateView):
    """
    受講者の情報修正
    """
    template_name = 'lessonmgmt/customer_update.html'
    model = Customer
    form_class = CustomerForm
    success_url = reverse_lazy('lessonmgmt:customer_list')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(
            self.request, '「{}」を更新しました'.format(form.instance))
        return result

class CustomerDeleteView(DeleteView):
    """
    受講者の削除
    """
    template_name = 'lessonmgmt/customer_confirm_delete.html'
    model = Customer
    form_class = CustomerForm
    success_url = reverse_lazy('lessonmgmt:customer_list')

    def delete(self, request, *args, **kwargs):
        try:
            result = super().delete(request, *args, **kwargs)
        except models.ProtectedError:
            messages.error(
                self.request, '「{}」は削除できませんでした'.format(self.object))
            return redirect('lessonmgmt:customer_list')

        messages.success(
            self.request, '「{}」を削除しました'.format(self.object))
        return result

lessonmgmt/views/invoice_view.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.views.generic.edit import FormView
from django.views.generic import TemplateView

from lessonmgmt.models.lessonhistory import *
from lessonmgmt.forms.selectmonth_form import *
from lessonmgmt.views.customer_lesson_history_table import *

import datetime
from dateutil.relativedelta import relativedelta

# Create your views here.
class InvoiceView(FormView):
    """
    請求一覧の月指定用の選択フォームを表示
    """
    template_name = 'lessonmgmt/invoice_list.html'
    form_class = SelectMonthForm # [teldren] 月の選択リスト用フォーム

    def get_context_data(self, **kwargs):
        form = self.form_class(initial={'number': 3}) # [teldren] 現在＋3ヶ月分を表示
        context = super().get_context_data(**kwargs) # はじめに継承元のメソッドを呼び出す
        context['form'] = form
        return context

class InvoiceFilterView(TemplateView):
    """
    請求一覧の選択月の結果表示
    """
    template_name = 'lessonmgmt/invoice_filter.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # はじめに継承元のメソッドを呼び出す
        self.select_month = self.request.GET.get('select_month', None) # [teldren] 検索月の指定。e.g. 2019-12-01
        if self.select_month is None:
            return context
        clht = CustomerLessonHistoryTable(self.select_month)
        invoices_df = clht.get_invoices()
        if len(invoices_df.index) == 0:
            context['invoices'] = invoices_df.to_dict(orient='records')
            return context
        invoices_df.loc[invoices_df['Total_Price'] == 0, 'lessonName'] = '-----'
        context['invoices'] = invoices_df.to_dict(orient='records')
        return context

lessonmgmt/views/menu_view.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.views.generic import TemplateView

# Create your views here.
class MenuView(TemplateView):
    template_name = 'lessonmgmt/menu_list.html'

templates/lessonmgmt/customer_list.html
{% extends "lessonmgmt/base.html" %}

{% block title %}顧客の一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">顧客の一覧</h4>
<a href="{% url 'lessonmgmt:customer_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">顧客名</th>
      <th scope="col">性別</th>
      <th scope="col">年齢</th>
      <th scope="col">操作</th>
    </tr>
  </thead>
  <tbody>
    {% for customer in object_list %}
    <tr>
      <td>{{ customer.customer_id }}</td>
      <td>{{ customer.name }}</td>
      <td>{{ customer.gender }}</td>
      <td>{{ customer.age }}</td>
      <td>
        <a href="{% url 'lessonmgmt:customer_update' customer.pk %}" class="btn btn-outline-primary btn-sm">修正</a>
        <a href="{% url 'lessonmgmt:customer_delete' customer.pk %}" class="btn btn-outline-danger btn-sm">削除</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

templates/lessonmgmt/customer_update.html
{% extends "lessonmgmt/base.html" %}
{% load bootstrap4 %}

{% block title %}顧客の追加・編集{% endblock title %}

{% block content %}
<h4 class="mt-4 mb-5 border-bottom">顧客の追加・編集</h4>
{% if object.pk %}
<form action="{% url 'lessonmgmt:customer_update' object.pk %}" method="post">
  {% else %}
  <form action="{% url 'lessonmgmt:customer_add' %}" method="post">
    {% endif %}
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <div class="form-group row">
      <div class="offset-md-3 col-md-9">
        <button type="submit" class="btn btn-primary">送信</button>
      </div>
    </div>
  </form>
  <a href="{% url 'lessonmgmt:customer_list' %}" class="btn btn-secondary btn-sm">戻る</a>
  {% endblock content %}

templates/lessonmgmt/lesson_confirm_delete.html
{% extends "lessonmgmt/base.html" %}
{% load bootstrap4 %}

{% block title %}ジャンルの削除{% endblock title %}

{% block content %}

<h5 class="mt-4 mb-5 border-bottom">削除していいですか？</h5>
<form action="{% url 'lessonmgmt:lesson_delete' object.pk %}" method="post">
  {% csrf_token %}
  <h5 class="mt-4 mb-5 border-bottom">{{ object }}</h5>
  <div class="form-group row">
    <div class="offset-md-3 col-md-9">
      <button type="submit" class="btn btn-primary">削除</button>
    </div>
  </div>
</form>
<a href="{% url 'lessonmgmt:lesson_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

templates/lessonmgmt/lesson_list.html
{% extends "lessonmgmt/base.html" %}

{% block title %}ジャンルの一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">ジャンルの一覧</h4>
<a href="{% url 'lessonmgmt:lesson_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">ジャンル名</th>
      <th scope="col">基本料金</th>
      <th scope="col">インクルージョン時間</th>
      <th scope="col">従量課金</th>
      <th scope="col">操作</th>
    </tr>
  </thead>
  <tbody>
    {% for lesson in object_list %}
    <tr>
      <td>{{ lesson.lesson_id }}</td>
      <td>{{ lesson.lessonName }}</td>
      <td>{{ lesson.basicCharge }}</td>
      <td>{{ lesson.includeHour }}</td>
      <td>{{ lesson.hourlyRate }}</td>
      <td>
        <a href="{% url 'lessonmgmt:lesson_update' lesson.pk %}" class="btn btn-outline-primary btn-sm">修正</a>
        <a href="{% url 'lessonmgmt:lesson_delete' lesson.pk %}" class="btn btn-outline-danger btn-sm">削除</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

templates/lessonmgmt/lesson_update.html
{% extends "lessonmgmt/base.html" %}
{% load bootstrap4 %}

{% block title %}ジャンルの追加・編集{% endblock title %}

{% block content %}
<h4 class="mt-4 mb-5 border-bottom">ジャンルの追加・編集</h4>
{% if object.pk %}
<form action="{% url 'lessonmgmt:lesson_update' object.pk %}" method="post">
  {% else %}
  <form action="{% url 'lessonmgmt:lesson_add' %}" method="post">
    {% endif %}
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <div class="form-group row">
      <div class="offset-md-3 col-md-9">
        e.g. [{"hour" : 0, "rate" : 1500}, {"hour" : 20, "rate" : 1000}, {"hour" : 35, "rate" : 800}]
      </div>
    </div>
    <div class="form-group row">
      <div class="offset-md-3 col-md-9">
        <button type="submit" class="btn btn-primary">送信</button>
      </div>
    </div>
  </form>
  <a href="{% url 'lessonmgmt:lesson_list' %}" class="btn btn-secondary btn-sm">戻る</a>
  {% endblock content %}

templates/lessonmgmt/lessonhistory_list.html
{% extends "lessonmgmt/base.html" %}

{% block title %}受講履歴の一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">受講履歴の一覧</h4>
<a href="{% url 'lessonmgmt:lessonhistory_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">顧客ID</th>
      <th scope="col">顧客名</th>
      <th scope="col">ジャンル名</th>
      <th scope="col">受講日</th>
      <th scope="col">受講時間</th>
      <th scope="col">操作</th>
    </tr>
  </thead>
  <tbody>
    {% for lessonhistory in object_list %}
    <tr>
      <td>{{ lessonhistory.customerName.customer_id }}</td>
      <td>{{ lessonhistory.customerName }}</td>
      <td>{{ lessonhistory.lessonName }}</td>
      <td>{{ lessonhistory.lessonDate }}</td>
      <td>{{ lessonhistory.lessonHours }}</td>
      <td>
        <a href="{% url 'lessonmgmt:lessonhistory_update' lessonhistory.pk  %}" class="btn btn-outline-primary btn-sm">修正</a>
        <a href="{% url 'lessonmgmt:lessonhistory_delete' lessonhistory.pk %}" class="btn btn-outline-danger btn-sm">削除</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

templates/lessonmgmt/lessonhistory_update.html
{% extends "lessonmgmt/base.html" %}
{% load bootstrap4 %}

{% block title %}受講履歴の追加・編集{% endblock title %}

{% block content %}
<h4 class="mt-4 mb-5 border-bottom">受講履歴の追加・編集</h4>
{% if object.pk %}
<form action="{% url 'lessonmgmt:lessonhistory_update' object.pk %}" method="post">
  {% else %}
  <form action="{% url 'lessonmgmt:lessonhistory_add' %}" method="post">
    {% endif %}
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <div class="form-group row">
      <div class="offset-md-3 col-md-9">
        <button type="submit" class="btn btn-primary">送信</button>
      </div>
    </div>
  </form>
  <a href="{% url 'lessonmgmt:lessonhistory_list' %}" class="btn btn-secondary btn-sm">戻る</a>
  {% endblock content %}

templates/lessonmgmt/menu_list.html
{% extends "lessonmgmt/base.html" %}

{% block title %}メニュー{% endblock title %}

{% block content %}
<ul>
  <li><a href="{% url 'lessonmgmt:lesson_list' %}" class="list-group-item">ジャンル一覧</a></li>
  <li><a href="{% url 'lessonmgmt:customer_list' %}" class="list-group-item">顧客一覧</a></li>
  <li><a href="{% url 'lessonmgmt:lessonhistory_list' %}" class="list-group-item">レッスン受講記録</a></li>
  <li><a href="{% url 'lessonmgmt:invoice_search_form' %}" class="list-group-item">月別請求一覧</a></li>
  <li><a href="{% url 'lessonmgmt:report_search_form' %}" class="list-group-item">レポート</a></li>
</ul>

{% endblock content %}

templates/lessonmgmt/report_genre_gender.html
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">ジャンル名</th>
      <th scope="col">性別</th>
      <th scope="col">レッスン時間</th>
      <th scope="col">受講者数</th>
      <th scope="col">売上</th>
    </tr>
  </thead>
  <tbody>
    {% for report in reports_genre_gender %}
    <tr>
      <td>{{ report.lessonName }}</td>
      <td>{{ report.gender }}</td>
      <td>{{ report.lessonHours }}</td>
      <td>{{ report.customerCount }}</td>
      <td>{{ report.Total_Price }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>